lid_ds/core/objects/victim.py, lid_ds/core/scenario.py, lid_ds/utils/docker_utils.py, setup.py
=> logging resources (Issue26)

scenarios/Bruteforce_CWE-307/exploit/exploit.py, scenarios/Bruteforce_CWE-307/normal/client.py, scenarios/CVE-2014-0160/exploit/exploit.py, scenarios/CVE-2014-0160/normal/client.py, scenarios/EPS_CWE-434/exploit/exploit.py, scenarios/EPS_CWE-434/normal/download_images.py, scenarios/EPS_CWE-434/normal/normal.py, scenarios/PHP_CWE-434/exploit/exploit.py, scenarios/PHP_CWE-434/normal/normal.py
by:
- adding if main to scripts
- describing behaviour in comments
- adding docstrings to functions
=> improved code quality in Scenarios Bruteforce, 2014, EPS and PHP

scenarios/Bruteforce_CWE-307/victim/Dockerfile, scenarios/CVE-2014-0160/victim/Dockerfile, scenarios/EPS_CWE-434/exploit/Dockerfile, scenarios/EPS_CWE-434/normal/Dockerfile, scenarios/PHP_CWE-434/exploit/Dockerfile, scenarios/PHP_CWE-434/victim/Dockerfile, scenarios/ZipSlip/victim/Dockerfile
moved updates to same line as installs
all scenarions were tested and still work
=> Fix dockerfiles

lid_ds/core/collector/collector.py, lid_ds/core/objects/meta.py, lid_ds/core/scenario.py
Added possibility to add exploit name to Scenario.
If none is given name is  "default".
=> Attack name

lid_ds/sim/dockerize.py
=> Added HTTPError Exception to logger loop

scenarios/CVE-2018-3760/README.md, scenarios/CVE-2018-3760/main.py, scenarios/CVE-2020-13942/README.md, scenarios/CVE-2020-13942/main.py, scenarios/CVE-2020-23839/README.md, scenarios/CVE-2020-23839/main.py, scenarios/EPS_CWE-434/README.md, scenarios/EPS_CWE-434/main.py, scenarios/PHP_CWE-434/README.md, scenarios/PHP_CWE-434/main.py
- CVE-2018-3760
- CVE-2020-13942
- CVE-2020-23839
- EPS_CWE-434
- PHP_CWE-434
closes #148
=> updated argument handling and readme files for scenarios:

scenarios/CVE-2018-3760/main.py
=> #120 sanity CVE 2018 3760

scenarios/CVE-2020-23839/main.py
=> sanity check CVE-2020-23839

scenarios/PHP_CWE-434/main.py, scenarios/PHP_CWE-434/normal/normal.py
=> sanity check php-cwe-434

scenarios/CVE-2020-13942/README.md, scenarios/CVE-2020-13942/main.py
=> sanity CVE-2020-13942

scenarios/CWE-89-SQL-injection/README.md, scenarios/CWE-89-SQL-injection/main.py
=> Sanity sql injection

scenarios/Juice-Shop/README.md, scenarios/Juice-Shop/main.py
=> Sanity juiceshop

Tools/calc_statistic_resource.py, Tools/data_loader.py, Tools/resource_statistic.py
Added calculation of resource statistic and small fix for creation of Recording.
=> Resource statistics

algorithms/ids.py, algorithms/main_example.py
#205 
using unix time in seconds
- new performance values: false negatives, true positives (correctly detected alarms) and detection rate on file level based on  given number of exploits
- new get_plotting_data() for upcoming plot class
=> performace measurement on file level

algorithms/ids.py, algorithms/main_example.py, algorithms/score_plot.py
(please merge #231 beforehand)
=> new class for plotting #208

algorithms/features/test/test_stream_ngram_extractor.py, algorithms/features/test/test_threadID_extractor.py, algorithms/features/test/test_w2v_embedding.py, algorithms/features/w2v_embedding.py
added tests for features and n_gram stream feature
=> #202 feature tests

algorithms/ids_som_main_2021.py, dataloader/dataloader_factory.py, dataloader/test/test_dataloader_factory.py
example usage can be found in ids_som_main.py
=> implemented data loader factory

algorithms/decision_engines/base_decision_engine.py, algorithms/decision_engines/lstm.py, algorithms/ids.py, algorithms/performance_measurement.py
* extend base decision engine with val_on
* add val_data to ids.train method
* add validation loop to lstm
* fix bug in performance measurement
=> Updated IDS and Base Decision Engine to enable validation data

algorithms/features/impl/return_value.py, algorithms/features/impl/test/test_return_value.py
Extension of existing feature.
=> added return of -1 on certain error codes

algorithms/features/impl/syscalls_in_time_window.py, algorithms/features/impl/test/test_syscalls_in_time_window.py, algorithms/ids_som_main.py
syscall in time window feature inkl test an neue Architektur angepasst
=> Syscalls in time window update

tools/return_value_statistics.py
Berechnung von Statistiken zu zurückgegebenen bytewerten für bestimmte syscalls.
=> Return value statistic

algorithms/decision_engines/ae.py, algorithms/features/impl/one_hot_encoding.py, algorithms/features/impl/w2v_embedding.py, algorithms/ids_ae_main.py, dataloader/dataloader_factory.py
- Autoencoder hinzugefügt
- DR sehr schlecht
- trotzdem erstmal der PR
- Word2Vec Embedding - speichert jetzt auch die Anzahl der Epochen mit im Dateinamen ab
=> Autoencoder DE

algorithms/performance_measurement.py
=> Fixed alarm count bug

algorithms/decision_engines/som.py, algorithms/ids_som_main.py
=> added som size parameter

algorithms/decision_engines/mlp.py, algorithms/ids_mlp_main.py
implemented new Building Block for multi layer perceptron using pytorch
closes #300
=> #300 mlp bb

algorithms/decision_engines/ae.py, algorithms/ids_ae_main.py
also updated the ae main file for testing
=> fixed bug - AE does now stop on val loss

algorithms/features/impl/collect_syscall.py, algorithms/features/impl/test/test_collect_syscall.py
If first system call is closing syscall, then None is returned and syscall will not be considered further.
=> 328 bug in collect syscall

algorithms/features/impl/PositionInFile.py, algorithms/features/impl/PositionalEncoding.py, algorithms/features/impl/flags.py, algorithms/features/impl/mode.py, algorithms/features/impl/ngram.py, algorithms/features/impl/processID.py, algorithms/features/impl/return_value.py, algorithms/features/impl/syscall_name.py, algorithms/features/impl/threadID.py, algorithms/features/impl/thread_change_flag.py, algorithms/features/impl/timestamp.py, algorithms/features/impl/unknown_flags.py
Removed singleton metaclass from most BBs because this caused errors in our tests. Additionally providing new implementation for ngram BB - it is faster due to time command and cProfiler.
=> Test problems with Singleton and NGram performance enhancement.

algorithms/features/impl/return_value.py, algorithms/features/impl/test/test_return_value.py
* Return Value standard mäßig mit min_max_scaling -> um vorhandene Verwendung nicht zu verändern
=> added option to not scale return value

algorithms/ids.py, algorithms/performance_measurement.py
Missing new_recording call of performance in ids.py
=> BUG: parallel detect cfps != detect cfps

algorithms/decision_engines/torus_som.py, algorithms/ids_torus_som_main.py, algorithms/util/toroidalsom.py
works but detects nothing
closes #356
=> 356 implemented toroidal SOM

algorithms/alarms.py, algorithms/features/impl/collect_syscall.py, algorithms/features/impl/syscalls_in_time_window.py, algorithms/features/impl/test/test_avg.py, algorithms/features/impl/test/test_collect_syscall.py, algorithms/features/impl/test/test_int_embedding.py, algorithms/features/impl/test/test_maximum.py, algorithms/features/impl/test/test_minimum.py, algorithms/features/impl/test/test_multiply.py, algorithms/features/impl/test/test_ngram.py, algorithms/features/impl/test/test_ngram_minus_one.py, algorithms/features/impl/test/test_path_evilness.py, algorithms/features/impl/test/test_select.py, algorithms/features/impl/test/test_stream_sum.py, algorithms/features/impl/test/test_sum.py, algorithms/features/impl/test/test_syscall_name.py, algorithms/features/impl/test/test_syscalls_in_time_window.py, algorithms/features/impl/test/test_threadID.py, algorithms/features/impl/test/test_thread_change_flag.py, algorithms/features/impl/test/test_time_delta.py, algorithms/features/impl/test/test_unknown_flag.py, algorithms/features/impl/test/test_w2v_embedding.py, algorithms/features/impl/time_delta.py, algorithms/features/impl/unknown_flags.py, algorithms/test/test_alarms.py, dataloader/syscall_2019.py
=> 318 extent tests

algorithms/decision_engines/mlp.py, algorithms/ids_ae_main.py, algorithms/ids_mlp_main.py, algorithms/ids_real_world.py, algorithms/ids_som_main.py, algorithms/ids_torus_som_main.py, algorithms/som_generate_alarms_main.py, algorithms/stide_generate_alarms_main.py
This is a fix for the various example....main.py files. It updates the usage of the features, makes use of faster parallel detection and improves reproducability for Multi-Layer-Perceptron and AutoEncoder.
=> Fix(Example-Files): Updating example files for different decision engines. 

algorithms/decision_engines/aetf.py, algorithms/ids.py, algorithms/ids_ae_main.py
- did this to check why the AE has performance problems, does it depend on the used framework?
- it does seem to produce the same (almost the same) results
- see ids_ae_main.py 
- used OHE here to exclude Word2Vec factors
- both implementations generate almost every time bad results for CVE-2017-7529 (19/21)
- sometimes the results are almost perfect...
- seems to depend on learning time? or initialisation?
- we need some experiments on this
=> added simple Keras / Tensorflow implementation which does the same AE calculations as the torch one

algorithms/ids_som_main.py, algorithms/persistance.py
you will need to set following env vars to use it:
* LID_DS_MONGO_IP
* LID_DS_MONGO_USER
* LID_DS_MONGO_PW
=> added mongodb persistance function

algorithms/decision_engines/transformer.py, algorithms/decision_engines/transfromer.py, algorithms/ids_transformer_main.py
This is just to sync the work done on my fork.
WIP
=> 252 transformer based Decision engine

algorithms/features/impl/aabb.py, algorithms/features/impl/k_center.py, algorithms/features/impl/nearest_neighbour.py, algorithms/features/impl/test/test_aabb.py, algorithms/features/impl/test/test_k_center.py, algorithms/features/impl/test/test_nearest_neighbour.py, algorithms/ids_aabb_main.py, algorithms/ids_k_center_main.py, algorithms/ids_nearest_neighbour_main.py
added all three new multidimensional threshold BBs
closes #419
=> 419 new threshold bbs
